# Docker Compose Development
# Adaptive Learning Ecosystem - EbroValley Digital
# Configuración optimizada para desarrollo

version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: adaptive-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: adaptive_learning
      POSTGRES_USER: adaptive_user
      POSTGRES_PASSWORD: adaptive_password_2024
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/postgresql_setup.py:/docker-entrypoint-initdb.d/init.py
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adaptive_user -d adaptive_learning"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - adaptive-dev

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: adaptive-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - adaptive-dev

  # AI Tutor Service (Development mode)
  ai-tutor-service:
    build:
      context: ./services/ai-tutor-service
      dockerfile: Dockerfile
    container_name: adaptive-ai-tutor-dev
    restart: "no"
    environment:
      - PYTHONUNBUFFERED=1
      - AI_TUTOR_PORT=5001
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=adaptive_learning
      - POSTGRES_USER=adaptive_user
      - POSTGRES_PASSWORD=adaptive_password_2024
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/ai-tutor-service:/app
      - ./shared:/app/shared:ro
    networks:
      - adaptive-dev
    profiles:
      - full

  # Progress Tracking Service (Development mode)
  progress-tracking-service:
    build:
      context: ./services/progress-tracking-service
      dockerfile: Dockerfile
    container_name: adaptive-progress-dev
    restart: "no"
    environment:
      - PYTHONUNBUFFERED=1
      - PROGRESS_TRACKING_PORT=5004
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=adaptive_learning
      - POSTGRES_USER=adaptive_user
      - POSTGRES_PASSWORD=adaptive_password_2024
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5004:5004"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/progress-tracking-service:/app
      - ./shared:/app/shared:ro
    networks:
      - adaptive-dev
    profiles:
      - full

  # Assessment Service (Development mode)
  assessment-service:
    build:
      context: ./services/assessment-service
      dockerfile: Dockerfile
    container_name: adaptive-assessment-dev
    restart: "no"
    environment:
      - PYTHONUNBUFFERED=1
      - ASSESSMENT_PORT=5005
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=adaptive_learning
      - POSTGRES_USER=adaptive_user
      - POSTGRES_PASSWORD=adaptive_password_2024
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5005:5005"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/assessment-service:/app
      - ./shared:/app/shared:ro
    networks:
      - adaptive-dev
    profiles:
      - full

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  adaptive-dev:
    driver: bridge